BulkBookDj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls"))
]

main/urls.py
from django.urls import path
from main.views import index, category

app_name = 'main'

urlpatterns = [
    path('', index, name="home"),
    path('category', category, name="category")
]

main/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Category(models.Model):

    id = models.AutoField(primary_key=True)
    name = models.CharField(null=False, max_length=250)
    display_order = models.IntegerField()
    date_created = models.DateTimeField(default=timezone.now)

main/views.py
from django.shortcuts import render
from main.models import Category

# Create your views here.
def index(request):
    return render(request, 'index.html')

def category(request):
    category_obj = Category.objects.all()
    return render(request, "category.html", context={'categories': category_obj})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>BulkyBookApp</title>
        <link rel="stylesheet" href="{% static 'lib/bootstrap/dist/css/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/site.css' %}" />
        <link rel="stylesheet" href="{% static 'css/layout.css' %}" />
        <link rel="stylesheet" href="{% static 'css/bootswatch.css' %}" />
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'main:home' %}">BulkBookApp</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarColor02">
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'main:home' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'main:category' %}">Category</a>
                            </li>
                        </ul>
                        <form class="d-flex">
                            <input class="form-control me-sm-2" type="search" placeholder="Search">
                            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                {% block body %}{% endblock %}
            </main>
        </div>
        <footer class="footer text-muted bg-dark">
            <div class="container">
                &copy; 2025 - BulkBookApp
            </div>
        </footer>
        <script src="{% static 'lib/jquery/dist/jquery.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.min.js" integrity="sha384-G/EV+4j2dNv+tEPo3++6LCgdCROaejBqfUeNjuKAiuXbjrxilcCdDz6ZAVfHWe1Y" crossorigin="anonymous"></script>
        <script src="{% static 'js/site.js' %}"></script>
    </body>
</html>

templates/category.html
{% extends './base.html' %}

{% block body %}
<h1 class="display-4">Index Category</h1>
{% if categories %}
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Category Name</th>
            <th>Display Order</th>
        </tr>
    </thead>
    <tbody>
        {% for category in categories %}
            <tr>
                <td>{{ category.name }}</td>
                <td>{{ category.display_order }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>No category</p>
{% endif %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block body %}
<div class="text-center">
    <h1 class="display-4">Welcome to Mine</h1>
</div>
{% endblock %}